VERSION --parallel-load --shell-out-anywhere --use-chmod --use-host-command 0.6
# --use-registry-for-with-docker

IMPORT github.com/katt-org/p/lib:master AS lib

FROM lib+platform

ARG stack

main:
    COPY main.py .
    SAVE ARTIFACT main.py

fit:
    FROM lib+fit --stack=${stack} --target=github.com/katt-org/p/defn+main
