VERSION --parallel-load --shell-out-anywhere --use-chmod --use-host-command 0.6
# --use-registry-for-with-docker

IMPORT github.com/katt-org/p/lib:master AS lib

FROM lib+platform

ARG stack

meh:
    COPY main.py .

fit:
    FROM lib+apply --stack=${STACK} --target=meh
