VERSION 0.6

FROM registry.fly.io/defn:dev-tower

CDKTF_SYNTH:
    COMMAND
    RUN echo '{ "language": "python", "app": "poetry run python -m main" }' > cdktf.json
    COPY pyproject.toml poetry.lock .
    RUN ~/bin/e poetry install
    COPY main.py .
    RUN ~/bin/e poetry run python -m main
    SAVE ARTIFACT cdktf.out/stacks AS LOCAL stacks
    SAVE IMAGE --push registry.fly.io/defn:test_cdktf

TERRAFORM_INIT:
    COMMAND
    ARG stack
    COPY stacks/${stack}/* .
    RUN ~/bin/e terraform init
    SAVE IMAGE --push registry.fly.io/defn:test_init

TERRAFORM_PLAN:
    COMMAND
    ARG stack
    COPY stacks/${stack}/* .
    RUN ~/bin/e terraform init
    SAVE IMAGE --push registry.fly.io/defn:test_init

POETRY_UPDATE:
    COMMAND
    COPY pyproject.toml poetry.lock .
    RUN ~/bin/e poetry update
    SAVE ARTIFACT poetry.lock AS LOCAL poetry.lock
    SAVE IMAGE --push registry.fly.io/defn:test_update
