VERSION 0.6

FROM registry.fly.io/defn:dev-tower

platform:
    RUN echo '{ "language": "python", "app": "poetry run python -m main" }' > cdktf.json
    COPY pyproject.toml poetry.lock .
    RUN ~/bin/e poetry install
    SAVE IMAGE --push registry.fly.io/defn:test_platform

update:
    COPY pyproject.toml poetry.lock .
    RUN ~/bin/e poetry update
    SAVE ARTIFACT poetry.lock AS LOCAL poetry.lock

POETRY_UPDATE:
    COMMAND
    COPY pyproject.toml poetry.lock .
    RUN ~/bin/e poetry update
    SAVE ARTIFACT poetry.lock AS LOCAL poetry.lock
    SAVE ARTIFACT pyproject.toml AS LOCAL pyproject.toml
